### ISSUE TITLE
A regrettable good project

### ISSUE THREAD

**Issue by JasonKid-maker** [Sprheany/ai-song#3]
Unfortunately, due to an error in the Suno API and the cessation of maintenance and updates, this project has also become invalid.
I really hope the author can replace an available Suno API so that this project can run again

**Comment by Sprheany** [comment]
I test the functionality is working fine。
The example site is not generating music because the cookie is out of date, I have updated the cookie and redeployed it. 
I may not be able to update the cookie regularly, you can deploy it yourself and update the SUNO_COOKIE environment variable.
